import type { StreamCandidate } from "@liberty/contracts/domains/playback";
import { normalizedContentIdSchema } from "@liberty/contracts/shared/ids";
import { LATENCY_CEILING_MS } from "@liberty/media-engine";
import {
  classifyHost,
  DEFAULT_PROVIDER_HEALTH_POLICY,
  healthPriorScore,
  type RightsBasis
} from "@liberty/provider-sdk";
import { NonDeploymentEnvironment } from "../../../deployment-environment";

/* -------------------------------------------------------------------------
 * Where a session's candidates come from (PL-0501)
 *
 * THE SERVER RESOLVES; THE CLIENT NAMES. A request carries a content id and a
 * device capability profile, and nothing else (see `contract.ts`). Everything
 * that ends up as a URL in a response was produced on this side of the
 * boundary, by an adapter that established authorization first. That is product
 * invariant 1, and it is a property of the SHAPE of this module: a resolver is
 * a function of a normalized content id, so there is no parameter through which
 * a caller could suggest a stream.
 *
 * WHY THE SEAM EXISTS AT ALL rather than the route calling a provider directly:
 * `@liberty/provider-sdk`'s `AuthorizedMediaProvider` resolves candidates for a
 * `CatalogItemRef` -- a provider id, an external id and a rights basis -- and
 * nothing in this app yet maps a normalized content id onto one. That mapping
 * is a catalog/provider-registry question, not a session-API question, and
 * inventing an answer here would put provider configuration inside an HTTP
 * route. So the session API depends on the CAPABILITY, injectably, and the
 * registry lands behind it without this file changing.
 * ---------------------------------------------------------------------- */

/**
 * A URL an authorized session would hand to the player, with the one fact the
 * outbound URL policy needs about where it came from.
 *
 * Separate from the `StreamCandidate` rather than flattened into it, because
 * the two have different lifetimes and different readers: the candidate is
 * metadata a provider stated and the ranking scores, and this is a
 * credential-bearing address that no ranking should ever see. `ranking.ts`
 * takes `StreamCandidate` and could not read this even by accident.
 *
 * `allowLoopback` mirrors `UrlPolicyOptions` in `@liberty/provider-sdk`, and it
 * is deliberately only HALF of the permission: loopback also requires the
 * deployment to say it is local. A source claiming to be local is a statement
 * about somebody's laptop, and honouring it alone in a hosted process would aim
 * this endpoint at our own admin ports.
 *
 * THIS IS THE SEAM FOR A SHORT-LIVED PLAYBACK CREDENTIAL, and it is the right
 * place for one: only the adapter that owns an origin can sign for it, so a
 * signed URL or a licence token belongs to whatever produces this record, with
 * the session's `expiresAt` bounding how long a client may hold it. Nothing
 * mints one today -- `uri` is whatever the resolver stated -- and no route,
 * bundle or fixture in this task contains a licence URL or key.
 */
export interface AuthorizedSource {
  readonly uri: string;
  /** `null` = the resolver could not state one. Never a guess. */
  readonly mimeType: string | null;
  /** Whether the SOURCE is declared local. Necessary for loopback, never sufficient. */
  readonly allowLoopback: boolean;
}

export interface AuthorizedCandidate {
  readonly candidate: StreamCandidate;
  readonly source: AuthorizedSource;
}

/**
 * What a resolver can answer.
 *
 * Four outcomes rather than a list-or-null, because they send a reader to four
 * different systems and the session response distinguishes them: an unknown id
 * is the catalog's problem, an unavailable provider is the provider's, an
 * unconfigured one is the operator's, and a resolved-but-empty list is a real
 * answer meaning "this title has no streams right now".
 *
 * A resolver may still throw -- it talks to a network -- and `issue-session.ts`
 * treats a throw as `provider-unavailable` without reading the error's text.
 */
export type AuthorizedCandidateResolution =
  | { readonly status: "resolved"; readonly candidates: readonly AuthorizedCandidate[] }
  | { readonly status: "not-found" }
  | { readonly status: "not-configured" }
  | { readonly status: "provider-unavailable"; readonly detail: string };

/**
 * `requestId` is generated by this server per request and is NOT read from an
 * inbound header. A client-chosen correlation id forwarded to a third party is
 * a client-chosen value in somebody else's logs, and `ProviderContext`'s own
 * documentation makes the same point about `profileId`.
 */
export interface ResolverContext {
  readonly requestId: string;
}

export type AuthorizedCandidateResolver = (
  contentId: string,
  context: ResolverContext
) => AuthorizedCandidateResolution | Promise<AuthorizedCandidateResolution>;

/* -------------------------------------------------------------------------
 * Development fixtures
 * ---------------------------------------------------------------------- */

/**
 * Where fixture streams are served from.
 *
 * READ HERE AND NOWHERE ELSE. `apps/web/src/app/watch/watch-session.ts` used to
 * read the same variable to build its own copy of these fixtures, and the note
 * that once stood here asked the next reader to keep the two in step -- two
 * fixture origins would have meant the watch page and the session API disagreed
 * about what "the dev rig" is. The watch route now imports
 * `resolveAuthorizedCandidates` instead of restating it, so there is one reader
 * and the agreement is structural rather than remembered.
 *
 * `.invalid` is reserved by RFC 2606 and resolves
 * nowhere, so the default can never accidentally reach a real host -- the
 * fixtures fail, failover walks all three, and the reason trail shows the whole
 * sequence, which is more useful than a player that silently does nothing.
 *
 * OPERATOR-SUPPLIED AND THEREFORE UNTRUSTED AS A URL, even though the operator
 * is not an attacker: a typo is as capable of aiming this at 169.254.169.254 as
 * malice is. Nothing here sanitises it. It is composed into a URL below in a way
 * that cannot be subverted by a query string or a fragment, and it is then
 * REFUSED, with a named reason, by `issue-session.ts`'s `checkUrl` gate -- the
 * same outbound URL policy the provider SDK runs. Stripping embedded credentials
 * or rewriting a private host here would be worse than leaving them: it would
 * make a misconfigured origin silently WORK, and the gate that exists to report
 * it would never fire.
 */
const FIXTURE_MEDIA_ORIGIN = process.env.LIBERTY_FIXTURE_MEDIA_ORIGIN ?? "https://fixtures.invalid";

const FIXTURE_PROVIDER = "fixture";

/**
 * The shape an internal rights reference is allowed to have.
 *
 * A `RightsBasis` carries a CATEGORY -- `rights`, plus the `basis` KIND, both
 * closed vocabularies `@liberty/provider-sdk` owns and checks -- and a
 * REFERENCE. The reference is an OPAQUE INTERNAL IDENTIFIER: it names a record
 * in the operator's own rights register and means nothing to anyone who does not
 * hold that register.
 *
 * IT IS OPAQUE BECAUSE THE AGREEMENTS THEMSELVES ARE NOT THIS REPOSITORY'S TO
 * CARRY. No licence body, no counterparty, no scope, no term dates and no URL
 * may be written into a rights basis. What is left is the category, which is the
 * part the engine actually enforces, plus an identifier that lets the operator
 * find the paperwork somewhere this repository cannot see. It matters downstream
 * too: `describeRightsBasis` in `@liberty/provider-sdk` renders the reference
 * into a human line for reason trails and logs, so whatever is written here is
 * something a bug-report screenshot can carry out of the building.
 *
 * WHAT THIS PATTERN DOES AND DOES NOT ESTABLISH, stated exactly, because a
 * comment that overclaims a check is worse than having no check. It admits only
 * lowercase alphanumeric groups joined by single hyphens, so it MECHANICALLY
 * excludes whitespace and prose, any URL (there is no `:` and no `/` in it),
 * userinfo or an address (`@`), and anything carrying capitals or punctuation.
 * It CANNOT tell whether a conforming token is a counterparty name, a date or a
 * contract title: `acme-tv-2026-emea` matches it. Those are refused by the
 * rights review, and the rule is written here so that review has one place to
 * point at.
 *
 * NOTHING PARSES OR BRANCHES ON THE VALUE. It is checked for shape and carried;
 * no code in this app splits it, reads a prefix out of it or decides anything
 * from its content. An identifier that gets interpreted has stopped being an
 * identifier, and the interpretation becomes a rights decision taken by a string
 * parser.
 */
export const OPAQUE_RIGHTS_REFERENCE_PATTERN = /^[a-z0-9]{2,16}(?:-[a-z0-9]{1,16}){1,7}$/;

/**
 * The longest an internal reference may be.
 *
 * A register id is short and a sentence is not, so length is the one crude
 * signal that separates them. The pattern above would otherwise admit 135
 * characters, which is long enough to hold a description.
 */
export const MAX_RIGHTS_REFERENCE_LENGTH = 64;

/**
 * Shape only -- see `OPAQUE_RIGHTS_REFERENCE_PATTERN` for what that can and
 * cannot establish, and for why nothing here reads what the token says.
 */
export function isOpaqueRightsReference(value: string): boolean {
  return value.length <= MAX_RIGHTS_REFERENCE_LENGTH && OPAQUE_RIGHTS_REFERENCE_PATTERN.test(value);
}

/**
 * The fixture provider's reference: a reserved all-zero token.
 *
 * IT NAMES NO RECORD ANYWHERE, AND THAT IS THE POINT. There is no agreement
 * covering imaginary media on a host that resolves nowhere, so a reference that
 * pointed at one would be the same fabrication in a smaller font. This token is
 * the rights-register counterpart of the RFC 2606 `.invalid` default origin
 * beside it: well formed, unmistakably reserved, and impossible to confuse with
 * a real entry.
 *
 * IT REPLACES A SENTENCE, and the replacement is a correction rather than a
 * tidy-up. The reference used to be prose: it described where the media came
 * from, named an environment variable and cited a heading in `docs/E2E.md`. That
 * is a scope description rather than an identifier, it is exactly the class of
 * content a rights basis must not carry, and `describeRightsBasis` would have
 * put the first sixty characters of it into any trail that printed the basis.
 */
const FIXTURE_RIGHTS_REFERENCE = "lty-ref-00000000-0000-0000";

/* -------------------------------------------------------------------------
 * WHERE THE ENVIRONMENT GATE WENT, AND WHY THERE IS NO `FIXTURE_ENVIRONMENTS`
 * HERE ANY MORE.
 *
 * This module used to export `FIXTURE_ENVIRONMENTS`, an alias of
 * `NON_DEPLOYMENT_ENVIRONMENTS`, and then test it with
 * `FIXTURE_ENVIRONMENTS.includes(process.env.NODE_ENV ?? "")`. So did
 * `../resolve/handler.ts`. One array, two spellings of the same `.includes`,
 * and `issue-session.ts` reaching the same answer a third way through
 * `isLocalDeployment` -- which is a restatement of the classification even
 * though the values could not drift, and a restatement is what has to be kept
 * in step by hand.
 *
 * The allowlist is now expressed exactly once, in
 * `app/api/deployment-environment.ts`, and consumed rather than re-tested. That
 * module also decides the shape of the consumption, and the two shapes are
 * different on purpose:
 *
 *   - `isLocalDeployment()` for the callers that need a boolean to hand to
 *     `checkUrl`, or to decide whether a development-only route exists;
 *   - `NonDeploymentEnvironment.classify()` for THIS one, because what is gated
 *     here is not an input to a later check -- it is the construction of a
 *     rights claim. See `fixtureProvider`.
 * ---------------------------------------------------------------------- */

/**
 * Whether the configured origin names the machine this process runs on.
 *
 * DERIVED, never asserted, and that is a correction. Every fixture candidate
 * used to carry `allowLoopback: true` unconditionally, with a comment observing
 * that loopback also needs the deployment to say it is local. True, and it
 * defeated the design it cited: `url-policy.ts` requires TWO permissions
 * expressly because they have DIFFERENT OWNERS -- a source config and the
 * process environment -- so that "neither owner can grant loopback by
 * themselves". Hardcoding the source half left one owner, and that owner is
 * `NODE_ENV`, which is also what decides whether fixtures resolve at all. The
 * two independent conditions had collapsed into one variable.
 *
 * Reading it off the origin restores the separation and is the more honest
 * claim anyway: the source is local exactly when the operator pointed it at a
 * loopback host, and it is not local when they did not. `classifyHost` is the
 * provider SDK's classifier rather than a string test, so `127.0.0.1`,
 * `localhost`, `[::1]` and `[::ffff:7f00:1]` are one answer and a name that
 * merely looks local is not.
 */
function originIsLoopback(origin: string): boolean {
  try {
    return classifyHost(new URL(origin).hostname) === "loopback";
  } catch {
    /* Not a URL at all. Not loopback, and reported as `url_unparseable` by the
     * transport gate once it is composed into a candidate. */
    return false;
  }
}

/**
 * Joins the operator's origin to a fixture path.
 *
 * Built through `URL` rather than by string concatenation, which is what the
 * previous `${origin}/${contentId}/${file}` did. Three real configurations broke
 * it, none of them exotic: a trailing slash produced a doubled one, an origin
 * carrying a query (`https://rig.test/?v=2`) swallowed the whole path into the
 * query string, and a fragment discarded it entirely. In each case the resulting
 * URL passed the transport gate -- it is the operator's own public https host --
 * and pointed somewhere else, so the failure arrived as a 404 from the rig with
 * nothing in the reason trail to explain it.
 *
 * Search and hash are dropped for the same reason `defineStremioSource` drops
 * them: they are not part of the origin's identity, and keeping them would make
 * the derived paths inconsistent with the base they came from.
 *
 * USERINFO IS DELIBERATELY PRESERVED. `https://user:pass@rig.test` survives into
 * the composed URL and is refused downstream as `url_credentials_present`.
 * Stripping it here would turn a credential-bearing misconfiguration into a
 * working stream and silence the one check that names it.
 */
function fixtureUri(origin: string, contentId: string, file: string): string {
  try {
    const url = new URL(origin);
    url.search = "";
    url.hash = "";
    url.pathname = `${url.pathname.replace(/\/+$/, "")}/${contentId}/${file}`;
    return url.toString();
  } catch {
    /* Unparseable. Joined verbatim so the candidate still exists and the
     * transport gate reports `url_unparseable` against it, rather than this
     * module silently producing a shorter list nobody can account for. */
    return `${origin}/${contentId}/${file}`;
  }
}

/**
 * Three candidates so failover has somewhere to go, listed WORST-FIRST.
 *
 * If this list were already in preference order, a defect in the ranking or in
 * this route's mapping would be invisible, because the wrong answer and the
 * right one would look identical.
 *
 * EVERY MEDIA FACT IS `null`, AND THAT IS THE WHOLE CORRECTION HERE. These
 * candidates used to state `height: 720`/`1080`, `bitrateKbps: 2800`/`5200`/
 * `6000` and `videoCodec: "h264"`/`audioCodec: "aac"`. Nothing had inspected the
 * files -- they may not exist, and when they do exist they are whatever an
 * operator packaged -- so all four were invented, which is exactly what PL-0205
 * exists to prevent and what `mapping.ts` had already removed from the Stremio
 * adapter.
 *
 * The codecs were the harmful pair, and harmful in the specific way that file
 * records: h264/aac is the most widely supported combination in existence, so
 * claiming it made every fixture pass capability eligibility PRECISELY BECAUSE
 * the values were ones every device accepts, and `compatibilityOf` then labelled
 * the session `verified` -- the response told a player we had ESTABLISHED that
 * this decodes here, about a file nobody has opened. `null` produces
 * `unverified`, which is the true statement.
 *
 * The heights were not much better. 720 was read off a filename this module
 * chose, which is circular, and 1080 on `master.m3u8` and `manifest.mpd` is not
 * even the right SHAPE of claim: an adaptive manifest has a ladder of
 * renditions, not a height.
 *
 * It also makes the dev rig representative for the first time. Every real
 * adapter in this repository emits four `null`s, because no protocol here states
 * these facts; a fixture that stated all four was exercising a path no provider
 * can produce, and hiding the unverified path a developer most needs to see.
 *
 * The two remaining numbers cannot be `null` -- the contract requires them -- so
 * each states the value that cannot flatter the candidate:
 *
 *   - `healthScore` is the health policy's PRIOR, which is what a source with
 *     zero observations scores. `health.ts` argues that placement at length: it
 *     is exactly `PROVIDER_HEALTH_FLOOR`, which media-engine compares with a
 *     strict `<`, so an unobserved source sits ON the floor and survives by no
 *     margin at all. The old 0.82/0.94/0.97 were invented, and at weight 30 they
 *     were the largest single fabricated contribution to the ranking.
 *   - `estimatedLatencyMs` is the latency ceiling, so the penalty dimension is
 *     charged in FULL. `scoring.ts` states the rule and the reason: an unknown
 *     positive dimension earns nothing, but an unknown PENALTY that contributed
 *     zero would reward a candidate for withholding information. Nothing timed
 *     these, so nothing gets the benefit.
 *
 * What still differs between the three is `protocol`, which is a genuine fact
 * read off the path exactly as `deriveProtocol` reads it. So the ranking still
 * reorders the list (dash, hls, progressive) and the worst-first property still
 * has something to prove, while the hls/dash tie exercises the id tiebreak.
 *
 * `origin` is a parameter rather than only an environment read so tests can pin
 * it. A test whose expectations depend on an operator's `.env.local` is a test
 * that fails on one machine and passes on another.
 */
function fixtureCandidates(
  rightsBasis: RightsBasis,
  contentId: string,
  origin: string
): readonly AuthorizedCandidate[] {
  /*
   * Re-checked here even though `playbackSessionRequestSchema` already refuses a
   * non-normalized id before any resolver runs. An id is interpolated into a URL
   * path, and `..` is not stopped by percent-encoding (dots are unreserved), so
   * an unvalidated id could walk out of the origin's path prefix -- the same
   * reasoning `mapping.ts` gives for its redundant rights check. An empty list
   * rather than a throw: it lands as `no_candidates_resolved`, which is the
   * reversible direction.
   */
  if (!normalizedContentIdSchema.safeParse(contentId).success) return [];

  /*
   * FAIL CLOSED ON A REFERENCE OF UNREVIEWED SHAPE. Unreachable while
   * `FIXTURE_RIGHTS_REFERENCE` is the literal above -- it conforms, and this
   * module builds the only basis that reaches here -- and that is exactly what
   * it is for: an edit that replaces the token with a sentence, a URL or a
   * counterparty's name produces NO CANDIDATES instead of publishing the
   * sentence into a reason trail. A rights declaration nobody may read is not a
   * declaration worth serving.
   */
  if (!isOpaqueRightsReference(rightsBasis.reference)) return [];

  const rights = rightsBasis.rights;
  const allowLoopback = originIsLoopback(origin);
  const healthScore = healthPriorScore(DEFAULT_PROVIDER_HEALTH_POLICY);

  /**
   * Everything the same for all three, because nothing distinguishes them:
   * four `null`s -- the contract's word for unknown, never a placeholder -- plus
   * the two fields the contract will not let be unknown, each stating the value
   * that cannot flatter the candidate. Shared rather than repeated so a future
   * edit cannot make one fixture quietly more optimistic than its siblings.
   */
  const unmeasured = {
    height: null,
    bitrateKbps: null,
    videoCodec: null,
    audioCodec: null,
    estimatedLatencyMs: LATENCY_CEILING_MS,
    healthScore
  } as const;

  return [
    {
      candidate: {
        id: `${contentId}-progressive`,
        providerId: FIXTURE_PROVIDER,
        rights,
        protocol: "https",
        ...unmeasured
      },
      source: {
        uri: fixtureUri(origin, contentId, "720p.mp4"),
        mimeType: "video/mp4",
        allowLoopback
      }
    },
    {
      candidate: {
        id: `${contentId}-hls`,
        providerId: FIXTURE_PROVIDER,
        rights,
        protocol: "hls",
        ...unmeasured
      },
      source: {
        uri: fixtureUri(origin, contentId, "master.m3u8"),
        mimeType: "application/vnd.apple.mpegurl",
        allowLoopback
      }
    },
    {
      candidate: {
        id: `${contentId}-dash`,
        providerId: FIXTURE_PROVIDER,
        rights,
        protocol: "dash",
        ...unmeasured
      },
      source: {
        uri: fixtureUri(origin, contentId, "manifest.mpd"),
        mimeType: "application/dash+xml",
        allowLoopback
      }
    }
  ];
}

/**
 * The fixture provider, which cannot be obtained without proof that this process
 * is not a deployment.
 *
 * THIS ARGUMENT IS THE WHOLE RIGHTS CONTROL, so it is worth being precise about
 * what it does. The fixture candidates declare `owned` over media nothing has
 * ever opened. Nothing verifies that: there is no probe here, no manifest is
 * read, and `issue-session.ts` treats the value exactly as it treats any
 * adapter's -- membership of `PLAYABLE_RIGHTS` and no further question, because
 * the platform's model is that adapters establish authorization and the engine
 * ranks among what they established. An unverifiable declaration therefore has
 * exactly one real control, and it is that this path cannot run on a build that
 * ships.
 *
 * IT USED TO BE A CONDITION AND IS NOW A TYPE. The gate was
 * `FIXTURE_ENVIRONMENTS.includes(process.env.NODE_ENV ?? "")` in the resolver
 * below: correct, and deletable. Delete it and every fixture resolves in
 * production, and everything still compiles. That is not a hypothetical failure
 * mode here -- `watch/watch-session.ts` shipped a second copy of these fixtures
 * under NO environment condition at all, and `docs/E2E.md` recorded the
 * difference as intended behaviour.
 *
 * `NonDeploymentEnvironment` cannot be constructed outside
 * `app/api/deployment-environment.ts` (private constructor, private field, so
 * TypeScript compares it nominally), and the only way to obtain one is
 * `classify`, which answers `null` for every environment outside the allowlist.
 * A caller therefore cannot reach this function without handling that `null`.
 * The fabricated basis is a value that CANNOT BE BUILT in a deployment, rather
 * than a value that is built and then withheld.
 *
 * What it does not do is defend against an edit to these two modules. Nothing
 * in TypeScript can. What it defends against is the way this defect actually
 * recurs: a change somewhere else that quietly stops consulting the gate.
 *
 * A REMAINING GAP, recorded rather than papered over: a hosted deployment that
 * exports `NODE_ENV=development` and runs `next dev` still gets a witness.
 * Nothing here can distinguish that from a laptop, because it IS a development
 * build; the control for it is not shipping one.
 */
export interface FixtureProvider {
  /**
   * The `NODE_ENV` that admitted this provider.
   *
   * Reported, never re-tested. Carried so a caller that logs or asserts WHICH
   * environment authorised the fixtures reads the value the classification
   * actually used, instead of re-reading `process.env` and possibly reporting a
   * different one.
   */
  readonly environment: string;
  /**
   * The declaration every candidate below carries: a category the provider SDK's
   * own vocabularies recognise, plus an opaque reference. See
   * `OPAQUE_RIGHTS_REFERENCE_PATTERN` and `FIXTURE_RIGHTS_REFERENCE`.
   */
  readonly rightsBasis: RightsBasis;
  candidates(contentId: string, origin?: string): readonly AuthorizedCandidate[];
}

export function fixtureProvider(environment: NonDeploymentEnvironment): FixtureProvider {
  /*
   * Built here rather than at module scope, so the `owned` declaration does not
   * exist as a value in a process that never presented a witness. A module-level
   * constant would be constructed on import, in every environment, and the
   * argument above would be about who may READ it rather than about whether it
   * exists.
   *
   * `RightsBasis` is the provider SDK's type, so `operator-owned-master` is
   * checked against `RIGHTS_BASES_FOR_RIGHTS` rather than being a word chosen
   * here -- `authorized-candidates.test.ts` applies that table, because the
   * fixture provider does not go through `defineStremioSource`'s constructor.
   */
  const rightsBasis: RightsBasis = {
    rights: "owned",
    basis: "operator-owned-master",
    reference: FIXTURE_RIGHTS_REFERENCE
  };

  return {
    environment: environment.nodeEnv,
    rightsBasis,
    candidates: (contentId, origin = FIXTURE_MEDIA_ORIGIN) =>
      fixtureCandidates(rightsBasis, contentId, origin)
  };
}

/**
 * The resolver the route uses when nothing is injected.
 *
 * IN A DEPLOYMENT IT RESOLVES NOTHING, and that is the honest answer rather than
 * a gap: no provider registry is wired into this app yet, and serving fixtures
 * from a hosted deployment would publish an unverifiable `owned` declaration for
 * files that do not exist. `not-configured` is a distinct outcome precisely so
 * the operator's remedy ("configure a provider") is legible instead of arriving
 * as a generic empty result.
 *
 * The classification is read from the process boundary at CALL time, not at
 * module scope: a module-scope read freezes the answer to whatever the process
 * looked like when the route was first loaded, which in a serverless cold start
 * is not necessarily the request's environment.
 *
 * THE `null` CHECK BELOW IS NOT OPTIONAL AND CANNOT BE DROPPED. `classify`
 * returns `NonDeploymentEnvironment | null` and `fixtureProvider` takes the
 * non-null type, so removing this branch does not widen the gate -- it fails to
 * compile. It is also not a source config value and must not become one: a
 * fixture source that could declare itself production-worthy is the same mistake
 * `url-policy.ts` refuses to make with `localDeployment`.
 */
export const resolveAuthorizedCandidates: AuthorizedCandidateResolver = (contentId) => {
  const environment = NonDeploymentEnvironment.classify();
  if (environment === null) return { status: "not-configured" };
  return { status: "resolved", candidates: fixtureProvider(environment).candidates(contentId) };
};
